const SNAP_PHOTOSPREAD = "SNAP_PHOTOSPREAD";
const SAVE_PHOTOS = "SAVE_PHOTOS";
const SELECT_PHOTO_FROM_GALLERY = "SELECT_PHOTO_FROM_GALLERY";
const SNAP_PHOTOTEMPLATE = "SNAP_PHOTOTEMPLATE";
const SAVE_LEFT_EDGE_OF_DROPPED_PHOTO = "SAVE_LEFT_EDGE_OF_DROPPED_PHOTO";
const SET_FRAME_DROPPED_PHOTO_LANDED_ON = "SET_FRAME_DROPPED_PHOTO_LANDED_ON";

export {
  SNAP_PHOTOSPREAD,
  SNAP_PHOTOTEMPLATE,
  SAVE_PHOTOS,
  SELECT_PHOTO_FROM_GALLERY,
  SAVE_LEFT_EDGE_OF_DROPPED_PHOTO,
  SET_FRAME_DROPPED_PHOTO_LANDED_ON
};
